[PR] View listings UI
harismah/Dwella pull request #240
Opened 2024-11-07 06:30 UTC by CarsonSSk

1.  Created a new "View Listings" page to display all listings created by a specific user.
2.  Added "Edit" and "Remove" buttons for each listing on the "View Listings" page.
    - The "Edit" button links to the EditListing page for each specific listing, allowing users to modify details.
    - The "Remove" button triggers a confirmation popup before deleting the listing.

3. Delete Confirmation Popup:
    - Implemented a confirmation dialog to prevent accidental deletion of listings.
    - Upon confirmation, the selected listing is deleted, and a success message is displayed.

4. UI Enhancements:
    - Improved styling for buttons and components to align with the Figma design.
    - Updated footer and removed any erroneous characters affecting the layout.
    - Backend Integration:

5. Created backend route to fetch listings created by a specific user.
    - Integrated frontend components with this route to ensure user-specific listings are displayed.

related to EPIC 3 #136 
closes #260
closes #261
closes #262

2024-11-07 12:44 UTC, CarlaShawi commented
![image](https://github.com/user-attachments/assets/e9b2dc04-1e50-4ece-a248-4774db2d2edd)
![image](https://github.com/user-attachments/assets/a2900072-810e-43e5-9b1f-5098f3ecc0e3)

it is working as intended, however, for the loading, i suggest using the spinner class from the components directory.

2024-11-07 12:50 UTC, CarlaShawi requested changes
if you could use it and fix some responsiveness

2024-11-09 05:08 UTC, CarlaShawi approved these changes

2024-11-09 05:11 UTC, CarsonSSk commented
Thanks for the good feedback and the quick responses @CarlaShawi. Merging now.

2024-11-09 05:11 UTC, merged