[PR ENHANCEMENT] Prevent repeated API calls on explore page's search bar by adding debounce
harismah/Dwella pull request #355
Opened 2024-11-27 23:29 UTC by bt919

**Description:**
This PR adds a 500ms debounce to the explore page's search bar so that less API calls are made to the backend, and less loading states are shown to users as well.

**Summary of changes:**
  - Changed the onChange handler for the search bar to add debounce
  - Changed the search bar's onKeyDown and button's onClick handlers to inline (so those don't get debounced as well)
  - Moved the loading spinner further down into the component so the nav and other parts of the page still stays visible/interactive to the users

PR close #322

2024-11-28 19:11 UTC, MyWaterBottle requested changes
Good addition. Would change the debounce to a higher value to accomodate most typing speed.

2024-11-28 19:11 UTC, MyWaterBottle commented on client/src/pages/ExplorePage.jsx
> +    }, 200)
I would make this value higher as 200ms is very fast. Otherwise, great addition!

2024-11-28 19:28 UTC, bt919 commented on client/src/pages/ExplorePage.jsx
> +    }, 200)
Thanks for the feedback! should be good now

2024-12-02 16:51 UTC, MyWaterBottle approved these changes
Looks good! Can merge.

2024-12-02 21:58 UTC, merged